# DataFlux Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'dataflux'
    environment: 'development'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # DataFlux Services
  - job_name: 'dataflux-ingestion'
    static_configs:
      - targets: ['ingestion-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'dataflux-query'
    static_configs:
      - targets: ['query-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'dataflux-analysis'
    static_configs:
      - targets: ['analysis-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'dataflux-mcp'
    static_configs:
      - targets: ['mcp-server:2015']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'dataflux-web-ui'
    static_configs:
      - targets: ['web-ui:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Database Services
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  - job_name: 'weaviate'
    static_configs:
      - targets: ['weaviate:8080']
    metrics_path: '/v1/metrics'
    scrape_interval: 30s

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']
    metrics_path: '/db/manage/server/jmx/domain'
    scrape_interval: 30s

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # API Gateway
  - job_name: 'nginx'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: '/nginx_status'
    scrape_interval: 10s
